version: 2
executorType: docker
containerInfo:
  - image: markfirmware/ultibo-core:test-1.3.363-x64-1498715235731
stages:
  build:
    workDir: ~/ultibo-webstatus
    steps:
      - type: checkout
      - name: Build and test
        type: shell
        command: ./build.sh
      - name: List files
        type: shell
        command: ls -ltR
      - name: Save artifacts
        type: artifacts-store
        path: artifacts
        destination: ultibo-webstatus
