version: 2
executorType: docker
containerInfo:
  - image: markfirmware/ultibo-1.3.343-x64-1497653350699
stages:
  build:
    workDir: ~/ultibo-webstatus
    steps:
      - type: checkout
      - name: Build and test
        type: shell
        command: ./build.sh
      - name: List files
        type: shell
        command: ls -ltR
      - name: Save artifacts
        type: artifacts-store
        path: artifacts
        destination: ultibo-webstatus
